language: cpp
sudo: false

matrix:
 include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-6
    addons:
     apt:
      packages:
       - g++-6
      sources: &sources
       - ubuntu-toolchain-r-test
  - os: linux
    compiler: clang
    env: COMPILER=clang++-3.8
    addons:
     apt:
      packages:
       - clang-3.8
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
  - os: osx
    compiler: clang
    env: COMPILER=clang++

script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)
 
notifications:
 email: false