language: cpp

dist: trusty
sudo: required

matrix:
 include:

  # Linux builds
  # ------------

  # GCC builds
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-5
      - BUILD_TYPE=Release
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5

  # Clang builds
  - os: linux
    compiler: clang
    env: &clang_env
      - LLVM_VERSION=3.8.0
      - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
      - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
      - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
      - CXXFLAGS=-lc++
      - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
      - BUILD_TYPE=Release
    before_install: &clang_before_install
      - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
      - mkdir $HOME/clang-$LLVM_VERSION
      - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1

  # Mac OSX builds
  # --------------
  - os: osx
    osx_image: xcode 7.3
    compiler: clang
    env:
     - COMPILER=clang++
     - BUILD_TYPE=Release

script:
 - $COMPILER --version
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
 email: false
