language: cpp
sudo: false

matrix:
 include:

  # Linux builds
  # ------------

  # GCC builds
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-5
      - BUILD_TYPE=Release
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5

  # Clang builds
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-3.7
      - BUILD_TYPE=Release
    addons:
      apt:
        sources:
         - llvm-toolchain-precise-3.8
         - ubuntu-toolchain-r-test
        packages:
          - clang-3.8

  # Mac OSX builds
  # --------------
  - os: osx
    osx_image: xcode 7.3
    compiler: clang
    env:
     - COMPILER=clang++
     - BUILD_TYPE=Release

script:
 - $COMPILER --version
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
 email: false
