language: cpp
sudo: required
dist: precise

matrix:
 include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-6
    addons:
     apt:
      packages:
       - g++-6
      sources: &sources
       - ubuntu-toolchain-r-test       
  
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)