language: cpp
sudo: required
dist: trusty

matrix:
 include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-5
    addons:
     apt:
      packages:
       - g++-5
      sources: &sources
       - llvm-toolchain-precise-3.8
       - ubuntu-toolchain-r-test       
       
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)