language: cpp

dist: trusty
sudo: required

matrix:
 include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-6
    addons:
     apt:
      packages:
       - g++-6
      sources: &sources
       - ubuntu-toolchain-r-test
  - os: linux
    env:
     - LLVM_VERSION=3.8.0
     - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
     - COMPILER=clang++
     - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
     - CXXFLAGS=-lc++
     - PATH=$HOME/clang-$LLVM_VERSION/bin:$PATH
     - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
    before_install:
     - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
     - mkdir $HOME/clang-$LLVM_VERSION
     - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
  - os: osx
    osx_image: xcode 7.3
    compiler: clang
    env:
     - COMPILER=clang++

script:
 - uname -a
 - $COMPILER --version
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

after_success:
 - bash <(curl -s https://codecov.io/bash)
 
notifications:
 email: false