version: 0.1.{build}

environment:
 matrix:
  # VS 2015
  - platform: x86
    GENERATOR: Visual Studio 14 2015
  - platform: x64
    GENERATOR: Visual Studio 14 2015
  - platform: x64
    GENERATOR: Visual Studio 14 2015 Win64

  # VS 2013
  - platform: x86
    GENERATOR: Visual Studio 12 2013
  - platform: x64
    GENERATOR: Visual Studio 12 2013
  - platform: x64
    GENERATOR: Visual Studio 12 2013 Win64

# Prevent useless warnings from Xamarin targets
# See http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
 - cmake -version
 - mkdir build
 - cd build
 - cmake -G "%GENERATOR%" ..
 - cmake --build . --config "Release"
 - cmake --build . --config "Debug"

test_script:
 - cd bin
 - dir
 - otl-unit-test.exe
 - otl-unit-test-d.exe
