#!/bin/sh

rm -rf build
mkdir build
cd build

if [ $# -gt 1 ]; then
	if [ $1 = GCC ]; then		
		cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$2
		make
		make install
	elif [ %1 = CLANG ]; then
		cmake .. -G "Clang" -DCMAKE_BUILD_TYPE=$2
		make
		make install
	fi
fi

cd ..