#!/bin/sh
set -e

rm -rf build
mkdir build
cd build

if [ $# -gt 1 ]; then
	if [ $1 = GCC ]; then		
		cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$2
		make
		make install
		cd bin
		if [ $2 = Debug ]; then
			otl-test-d.exe
		elif [ %2 = Release ]; then
			otl-test.exe
		fi	
	elif [ $1 = CLANG ]; then
		cmake .. -G "Clang" -DCMAKE_BUILD_TYPE=$2
		make
		make install
	fi
fi

cd ..