#!/bin/sh

rm -rf build
mkdir build
cd build

if [ $# -gt 1 ]; then
	if [ $1 = GCC ]; then		
		cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$2 -DCMAKE_INSTALL_PREFIX="./install"
		make
	elif [ %1 = CLANG ]; then
	fi
fi

cd ..